%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.8

-ifndef('lighthouse-location-pb').
-define('lighthouse-location-pb', true).

-define('lighthouse-location-pb_gpb_version', "3.26.8").

-ifndef('LOCATION_PB_H').
-define('LOCATION_PB_H', true).
-record(location,
        {latitude               :: float() | integer() | infinity | '-infinity' | nan, % = 1
         longitude              :: float() | integer() | infinity | '-infinity' | nan, % = 2
         geohash                :: binary() | iolist() | undefined % = 3
        }).
-endif.

-endif.
